CREATE SCHEMA `top_store` DEFAULT CHARACTER SET utf8 ;

CREATE TABLE `top_store`.`product` (
  `ID` BIGINT(11) NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(255) NOT NULL,
  `Price` DOUBLE NOT NULL,
  `Deleted` VARCHAR(45) NULL DEFAULT 0,
   PRIMARY KEY (`ID`));
